SELECT (CASE
WHEN STATE = 1 THEN
'OPEN AND RUNNING'
WHEN STATE = 2 THEN
'OPEN AND SUSPENDED'
WHEN STATE = 3 THEN
'OPEN AND FAULTED'
WHEN STATE = 4 THEN
'CLOSED AND PENDING'
WHEN STATE = 5 THEN
'CLOSED AND COMPLETED'
WHEN STATE = 6 THEN
'CLOSED AND FAUTED'
WHEN STATE = 7 THEN
'CLOSED AND CANCELLED'
WHEN STATE = 8 THEN
'CLOSED AND ABORTED'
WHEN STATE = 9 THEN
'CLOSED AND STALE'
WHEN STATE = 10 THEN
'NON-RECOVERABLE'
ELSE
STATE || ''
END) AS STATE,
COUNT(*)AS NUM_OF_CUBE_INST, composite_name ,composite_revision, domain_name
FROM CUBE_INSTANCE
WHERE TRUNC(cast(creation_date AS date)) BETWEEN to_date('2010-01-01', 'YYYY-MM-DD') AND trunc(sysdate-90)
GROUP BY STATE, composite_name ,composite_revision, domain_name;
